name: ${project.name}
main: net.sradonia.bukkit.alphachest.AlphaChest
version: ${project.version}
author: kroimon
description: >
             Plugin that allows you to have virtual private chests.

commands:
  chest:
    description: Opens a virtual player-specific chest.
    usage: |
      /<command> - Opens your private chest.
      /<command> [player] - Opens someone else's chest.
  clearchest:
    description: Clears the contents of your AlphaChest.
    usage: |
      /<command> - Clears your private chest.
      /<command> [player] - Clears someone else's chest.
  savechest:
    description: Saves a specific player's AlphaChest to disk.
    usage: /<command> <player> - Saves a specified player's virtual chest.
    permission: alphachest.save
  savechests:
    description: Saves all AlphaChests to disk.
    permission: alphachest.save
  disposal:
    description: Opens a virtual disposal bin.
    aliases: [trash, bin]
    permission: alphachest.disposal
  workbench:
    description: Opens a virtual workbench.
    aliases: [craft, craftbox, craftingbox]
    permission: alphachest.workbench

permissions:
  alphachest.*:
    description: Gives access to the virtual chest and workbench.
    children:
      alphachest.chest: true
      alphachest.workbench: true
  alphachest.chest:
    description: Gives access to the virtual chest.
  alphachest.disposal:
    description: Gives access to the virtual disposal bin.
  alphachest.workbench:
    description: Gives access to the virtual workbench.

  alphachest.chest.creativeMode:
    description: Allows a player to open their virtual chest in creative mode.

  alphachest.keepOnDeath:
    description: Players with this permission keep the contents of their virtual chest on death.
  alphachest.dropOnDeath:
    description: Players with this permission drop the contents of their virtual chest on death.
  alphachest.clearOnDeath:
    description: Players with this permission lose the contents of their virtual chest on death.

  alphachest.admin:
    description: Allows to open and clear someone else's chest.
    default: op
  alphachest.save:
    description: Allows to save virtual chests.
    default: op